title: "Handbook"
#remote_theme: pmarsceill/just-the-docs
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Fork Contribute":
    - "//github.com/atishch/handbook"

theme: jekyll-theme-minimal

permalink: pretty
exclude: ["scripts/", "LICENSE.txt", "codes/", "README.md" , "/assets" , "/docs-stg" ]

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2018-2019 Atish Choudhury."
