apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
spec:
  containers:
  - name: elasticsearch-ctr
    image: elasticsearch
    resources:
      limits:
        cpu: "2000m" 
        memory: "2Gi"
      requests:
        cpu: "2000m"
        memory: "4Gi"